# This is a basic workflow to help you get started with Actions

name: Preview deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
        - name: RTM Authentication
        run: |
          curl --location --request POST 'https://api.azionapi.net/tokens' \
          --header 'Accept: application/json; version=3' \
          --header 'Authorization: Token Basic a3d9aa2d2b41cd11c98dae412ebced889b016521' \
          --header 'Content-Type: application/json'
  
      - name: GET EDGE Function by ID
        run: |
          curl --location --request GET 'https://api.azionapi.net/edge_functions/:id' \
          --header 'Accept: application/json; version=3' \
          --header 'Authorization: Token Basic a3d9aa2d2b41cd11c98dae412ebced889b016521' \
          --header 'Content-Type: application/json'

        - name: UPDATE EDGE Function by ID
          run: |
            curl --location --request POST 'https://api.azionapi.net/edge_functions/:id' \
            --header 'Accept: application/json; version=3' \
            --header 'Authorization: Token Basic a3d9aa2d2b41cd11c98dae412ebced889b016521' \
            --header 'Content-Type: application/json' \
            --data-raw '{
              "name": "Function Test API",
              "function_to_run": "js-test",
              "code": "{\r\n    async function handleRequest(request) {\r\n        return new Response(\"Hello world in a new response\");\r\n    }\r\n\r\n    addEventListener(\"fetch\", (event) => {\r\n        event.respondWith(handleRequest(event.request));\r\n    });\r\n}",
              "language": "javascript",
              "initiator_type": "edge_application",
              "json_args": {"key": "value"},
                "active": true
            }'


